Add GitHub Actions workflows files.
pantheon-systems/example-drops-8-composer pull request #468
Opened 2021-05-18 00:56 UTC by kporras07

Github Actions initial support added.

Several secrets should be added to Github Actions configuration to make it work:
- ADMIN_EMAIL
- ADMIN_PASSWORD
- ADMIN_USERNAME
- TERMINUS_TOKEN
- TERMINUS_SITE
- SSH_PRIVATE_KEY

I'm waiting for [this PR](https://github.com/garris/BackstopJS/pull/1317) to avoid compiling and updating git in runtime.

2021-05-18 22:23 UTC, greg-1-anderson commented
So, something I just thought of: if we merge this PR, then GitHub is going to try to run these tests on every PR made in this repository, right?  We don't want that. Maybe we should store the GitHub actions templates at a different path, and move it into position in the Terminus Build tools. There should also be a README with instructions for anyone working on it manually.

2021-05-19 01:23 UTC, kporras07 commented
@greg-1-anderson you're right. I just updated the files location. I'll do the same in the other PRs. Thanks

2021-05-21 01:44 UTC, kporras07 commented
I changed the way of updating git so that instead of taking ~2.5 min, it now takes ~10s.

2021-05-26 02:06 UTC, greg-1-anderson commented on README.md
> +# drop8kporras07
I think the changes to this file were unintentional

2021-05-26 02:07 UTC, greg-1-anderson requested changes
Just needs README fixed up, should be similar to https://github.com/pantheon-systems/example-drops-7-composer/pull/27/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

2021-05-26 20:31 UTC, kporras07 commented
@greg-1-anderson fixed by rebasing. Thanks.

I had messed up with the repo when testing build-tools integration.

2021-05-26 21:14 UTC, merged