[BUGS-5332] Turn off automation
pantheon-systems/example-drops-8-composer pull request #617
Opened 2022-12-01 15:50 UTC by jspellman814

2022-12-01 17:05 UTC, jspellman814 commented on README.md
> +The automation which ran daily and created PRs with updated `composer.lock` files has been disabled as of `12/1/22`. If at any point it is desired to re-enable this job, uncomment lines `277-286` in
build tools user audience

2022-12-02 15:29 UTC, CdrMarks requested changes

2022-12-02 15:29 UTC, CdrMarks commented on README.md
> +The automation which ran daily to check for composer updates has been disabled as of `12/1/22`. Build Tools users can re-enable automation to check for composer updates by uncommenting lines `277-286
```suggestion
The automation which ran daily to check for composer updates has been disabled as of `12/1/22`. Build Tools users can re-enable automation to check for composer updates by uncommenting the  `scheduled_update_check` in `.circleci/config.yml`.
```

2022-12-02 15:33 UTC, CdrMarks approved these changes

2022-12-02 15:42 UTC, merged